# Set up a Python environment in Travis

# Faster boot time using a container-based environment
# https://docs.travis-ci.com/user/ci-environment/
# sudo: False
# Opt into fully virtualized infrastructure
# cf http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/
sudo: required

language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5

addons:
  postgresql: "9.3"

services:
  - mysql
  - postgresql

install:
  - source setup.sh
  - setup_python
  - create_databases

script:
  - make test
