# Set up a Python environment in Travis

# Faster boot time using a container-based environment
# https://docs.travis-ci.com/user/ci-environment/
sudo: False

language: python

matrix:
  include:
    - python: 2.7
    # - python: 3.4     # TODO: restore
    # - python: 3.5     # TODO: restore

addons:
  postgresql: "9.3"

services:
  - mysql
  - postgresql

install:
  - source setup.sh

script:
  - make test
